from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

DEFAULT_MODELS = (
    "HuggingFaceTB/SmolVLM-256M-Instruct",
    "HuggingFaceTB/SmolVLM-500M-Instruct",
    "google/gemma-3-4b-it",
    "OpenGVLab/InternVL2-1B",
    "Qwen/Qwen2.5-VL-3B-Instruct",
    "Qwen/Qwen2-VL-2B-Instruct",
)
DEFAULT_DATASETS = ("textvqa", "docvqa", "chartqa")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run projected image-token Grad-CAM VQA subsets for a suite of models and rank clear outputs."
    )
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--subset-size", type=int, default=30)
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--split", default="train")
    parser.add_argument("--layer-index", type=int, default=0)
    parser.add_argument(
        "--activation-site",
        choices=("output", "input", "value"),
        default="output",
        help=(
            "Use selected decoder layer output, input, or self-attention value "
            "projection activations for Grad-CAM."
        ),
    )
    parser.add_argument("--device", default="auto")
    parser.add_argument("--max-new-tokens", type=int, default=12)
    parser.add_argument(
        "--target-mode",
        choices=("generated", "ground_truth"),
        default="generated",
    )
    parser.add_argument("--models", nargs="*", default=list(DEFAULT_MODELS))
    parser.add_argument("--datasets", nargs="*", default=list(DEFAULT_DATASETS))
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--sheet-k", type=int, default=3)
    parser.add_argument("--max-consecutive-failures", type=int, default=30)
    parser.add_argument("--no-skip-existing", action="store_true")
    return parser.parse_args()


def slugify_model(model_name: str) -> str:
    return model_name.replace("/", "__").replace(".", "_").replace("-", "_").replace(" ", "_")


def summary_is_complete(summary_path: Path, subset_size: int) -> bool:
    if not summary_path.exists():
        return False
    try:
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False
    return int(summary.get("subset_size_completed", 0)) >= subset_size


def run_command(command: list[str], *, env: dict[str, str]) -> int:
    print("[gradcam-suite] " + " ".join(command), flush=True)
    process = subprocess.run(command, env=env)
    return int(process.returncode)


def collect_suite_analysis(output_root: Path, model_statuses: list[dict[str, object]]) -> None:
    top_by_model_dataset: dict[str, dict[str, object]] = {}
    all_top_rows: list[dict[str, object]] = []
    for status in model_statuses:
        model_slug = str(status["model_slug"])
        model_name = str(status["model_name"])
        analysis_path = output_root / model_slug / "clearest_samples.json"
        if not analysis_path.exists():
            continue
        analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
        per_dataset = {}
        for dataset, rows in analysis.get("top_by_dataset", {}).items():
            enriched_rows = []
            for row in rows:
                enriched = dict(row)
                enriched["model_name"] = model_name
                enriched["model_slug"] = model_slug
                enriched_rows.append(enriched)
                all_top_rows.append(enriched)
            per_dataset[dataset] = enriched_rows
        top_by_model_dataset[model_slug] = {
            "model_name": model_name,
            "top_by_dataset": per_dataset,
            "contact_sheet": str(output_root / model_slug / "clearest_contact_sheet.jpg"),
        }

    all_top_rows.sort(key=lambda item: float(item.get("score", 0.0)), reverse=True)
    suite_analysis = {
        "selection_method": (
            "Per-model rankings were generated by scripts/analysis/select_dexar_clear_samples.py "
            "from projected image-token Grad-CAM sentence heatmaps."
        ),
        "top_by_model_dataset": top_by_model_dataset,
        "global_top_rows": all_top_rows[:30],
    }
    (output_root / "suite_clearest_samples.json").write_text(
        json.dumps(suite_analysis, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def main() -> None:
    args = parse_args()
    args.output_root.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env.setdefault("DEXAR_SHOW_PLOTS", "0")
    env.setdefault("MPLBACKEND", "Agg")
    env.setdefault("TRANSFORMERS_VERBOSITY", "error")
    env.setdefault("TOKENIZERS_PARALLELISM", "false")
    env.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
    env.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "1")
    env.setdefault("TQDM_DISABLE", "1")

    results: list[dict[str, object]] = []

    for model_name in args.models:
        model_slug = slugify_model(model_name)
        model_root = args.output_root / model_slug
        model_root.mkdir(parents=True, exist_ok=True)

        model_status: dict[str, object] = {
            "model_name": model_name,
            "model_slug": model_slug,
            "model_root": str(model_root),
            "datasets": [],
        }
        print(f"[gradcam-suite] model={model_name} root={model_root}", flush=True)

        for dataset in args.datasets:
            dataset_root = model_root / dataset
            summary_path = dataset_root / "summary.json"
            if not args.no_skip_existing and summary_is_complete(summary_path, args.subset_size):
                print(f"[gradcam-suite] skip complete {model_name} {dataset}", flush=True)
                model_status["datasets"].append(
                    {
                        "dataset": dataset,
                        "status": "skipped_complete",
                        "output_root": str(dataset_root),
                    }
                )
                continue

            command = [
                sys.executable,
                "demo/DEX-AR/run_gradcam_vqa_subset.py",
                "--model-name",
                model_name,
                "--dataset",
                dataset,
                "--split",
                args.split,
                "--subset-size",
                str(args.subset_size),
                "--offset",
                str(args.offset),
                "--layer-index",
                str(args.layer_index),
                "--activation-site",
                args.activation_site,
                "--device",
                args.device,
                "--max-new-tokens",
                str(args.max_new_tokens),
                "--target-mode",
                args.target_mode,
                "--output-root",
                str(dataset_root),
                "--max-consecutive-failures",
                str(args.max_consecutive_failures),
            ]
            returncode = run_command(command, env=env)
            model_status["datasets"].append(
                {
                    "dataset": dataset,
                    "status": "completed" if returncode == 0 else "failed",
                    "returncode": returncode,
                    "output_root": str(dataset_root),
                }
            )

        completed = all(
            summary_is_complete(model_root / dataset / "summary.json", args.subset_size)
            for dataset in args.datasets
        )
        if completed:
            analysis_command = [
                sys.executable,
                "scripts/analysis/select_dexar_clear_samples.py",
                "--root",
                str(model_root),
                "--top-k",
                str(args.top_k),
                "--sheet-k",
                str(args.sheet_k),
                "--datasets",
                *args.datasets,
            ]
            analysis_returncode = run_command(analysis_command, env=env)
            model_status["analysis_status"] = "completed" if analysis_returncode == 0 else "failed"
            model_status["analysis_returncode"] = analysis_returncode
        else:
            model_status["analysis_status"] = "skipped_incomplete"

        results.append(model_status)
        collect_suite_analysis(args.output_root, results)
        (args.output_root / "suite_summary.json").write_text(
            json.dumps({"results": results}, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    print(json.dumps({"results": results}, indent=2, ensure_ascii=False), flush=True)
    failures = [
        (result["model_name"], dataset_status["dataset"])
        for result in results
        for dataset_status in result.get("datasets", [])
        if dataset_status.get("status") == "failed"
    ]
    if failures:
        formatted = ", ".join(f"{model} on {dataset}" for model, dataset in failures)
        raise RuntimeError(f"Grad-CAM suite finished with failed runs: {formatted}")


if __name__ == "__main__":
    main()
